### ISSUE TITLE
Fix BLE connection interruptions after a while (status = 59)

### ISSUE THREAD

**Issue by mvidaldp** [neuroinfo-os/Traumschreiber#21]
Due to the connection parameters negotiation and connection intervals of 7.5ms the phone usually rejects this and ends up closing the connection with the BLE device after a while.

Explanation and solution suggestions:
https://stackoverflow.com/questions/35892288/android-bluetooth-low-energy-status-59
https://stackoverflow.com/questions/34617061/android-6-0-marshmallow-ble-connection-parameters

**Comment by denizmguen** [comment]
Did some testing:In both EEG-Droid as well as NRF Connect the Traumschreiber stops sending new packages at around 150s. I

**Comment by denizmguen** [comment]
I did some testing and stumbled upon the following: 

- According to my repeated manual measurements, the Traumschreiber disconnects after approximately150s in both apps; EEG-Droid and NRF Connect. 
- According to these 3  lines of [ code ](https://github.com/neuroinfo-os/Traumschreiber/blob/master/Traumschreiber_BLE_Code/main.c#L102-L104) , the traumschreiber requests a connection interval of 7.5ms every 35 seconds and disconnects after the 3rd try. Thus it is expected to consistently disconnect after about 140s (4*35s), being in the same ballpark as my manual measurements.
- The attached [log](https://github.com/neuroinfo-os/Traumschreiber/files/5147038/btsnoop_hci.log) shows that the connection parameter update gets rejected and the android device enforces a connection interval of 12.5ms three times throughout the connection span and the device disconnects at the fourth try.
- Since we do not use a connection interval of 7.5ms anyways and the data transmission seems to work fine for as long the Traumschreiber is connected, I suggest setting [`MIN_CONN_INTERVAL`](https://github.com/neuroinfo-os/Traumschreiber/blob/master/Traumschreiber_BLE_Code/main.c#L97) and [`MAX_CONN_INTERVAL` ](https://github.com/neuroinfo-os/Traumschreiber/blob/master/Traumschreiber_BLE_Code/main.c#L98) to 9 (12.5ms).

I cannot see how we should fix this from within the app, since android does not enable us to set the ble min connection interval below 12.5ms.
